"""Added global config with donation counter

Revision ID: 281888111a8c
Revises: 6d4eb6de04b4
Create Date: 2025-12-15 00:59:30.576846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281888111a8c'
down_revision = '6d4eb6de04b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_donated_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_config')
    # ### end Alembic commands ###
