"""Fresh start with whash

Revision ID: 6d4eb6de04b4
Revises: 
Create Date: 2025-12-06 03:29:43.983760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4eb6de04b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('whash', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_registry_phash'), ['phash'], unique=True)
        batch_op.create_index(batch_op.f('ix_image_registry_whash'), ['whash'], unique=False)

    op.create_table('image_consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('vote_real', sa.Integer(), nullable=True),
    sa.Column('vote_edited', sa.Integer(), nullable=True),
    sa.Column('vote_ai', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('image_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'url', name='uq_source')
    )
    op.create_table('provenance_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('analyzer', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'analyzer', 'data', name='uq_fact')
    )
    op.create_table('vote_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=64), nullable=False),
    sa.Column('choice', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'voter_id', name='uq_vote_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_history')
    op.drop_table('provenance_fact')
    op.drop_table('image_source')
    op.drop_table('image_consensus')
    with op.batch_alter_table('image_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_registry_whash'))
        batch_op.drop_index(batch_op.f('ix_image_registry_phash'))

    op.drop_table('image_registry')
    # ### end Alembic commands ###
