"""Add TinEyeResult table

Revision ID: 70fba85f0669
Revises: a3f3ecf40f45
Create Date: 2026-01-11 03:51:04.789741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fba85f0669'
down_revision = 'a3f3ecf40f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tineye_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('earliest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_shame_list', sa.Boolean(), nullable=False),
    sa.Column('matches_json', sa.Text(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tineye_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tineye_result_image_id'), ['image_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tineye_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tineye_result_image_id'))

    op.drop_table('tineye_result')
    # ### end Alembic commands ###
