"""Added indexes for parent_id and child_id in image containment table

Revision ID: a3f3ecf40f45
Revises: ab2b617f6b67
Create Date: 2025-12-30 03:44:47.511615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f3ecf40f45'
down_revision = 'ab2b617f6b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_containment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_containment_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_containment_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_containment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_containment_parent_id'))
        batch_op.drop_index(batch_op.f('ix_image_containment_child_id'))

    # ### end Alembic commands ###
