"""Remove TinEye persistence for TOS compliance

Revision ID: e4d558b920a0
Revises: 081ea53e0d97
Create Date: 2026-01-14 18:18:29.042642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4d558b920a0'
down_revision = '081ea53e0d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tineye_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tineye_result_image_id'))

    op.drop_table('tineye_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tineye_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_matches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filtered_match_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('earliest_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('on_shame_list', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('matches_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('searched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], name=op.f('tineye_result_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tineye_result_pkey'))
    )
    with op.batch_alter_table('tineye_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tineye_result_image_id'), ['image_id'], unique=True)

    # ### end Alembic commands ###
