"""Add index on ImageSource.url

Revision ID: f0d327233827
Revises: fb598b572026
Create Date: 2026-02-04 22:44:43.930500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d327233827'
down_revision = 'fb598b572026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_source_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_source_url'))

    # ### end Alembic commands ###
