"""Add SynthIDReport table

Revision ID: fb598b572026
Revises: a3f3ecf40f45
Create Date: 2026-02-04 19:23:46.522863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb598b572026'
down_revision = 'a3f3ecf40f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synth_id_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'voter_id', name='uq_synthid_report')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synth_id_report')
    # ### end Alembic commands ###
